// Dados mock para desenvolvimento do Clippr
import { Barber, Service, Booking, TimeSlot } from '@/types';

export const barbers: Barber[] = [
    {
        id: '1',
        name: 'Carlos Silva',
        avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop&crop=face',
        specialty: 'Cortes Modernos',
        rating: 4.9,
        reviewCount: 127,
        available: true,
    },
    {
        id: '2',
        name: 'André Santos',
        avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop&crop=face',
        specialty: 'Barba & Degradê',
        rating: 4.8,
        reviewCount: 98,
        available: true,
    },
    {
        id: '3',
        name: 'Rafael Costa',
        avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&h=150&fit=crop&crop=face',
        specialty: 'Cortes Clássicos',
        rating: 4.7,
        reviewCount: 156,
        available: false,
    },
    {
        id: '4',
        name: 'Lucas Oliveira',
        avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&h=150&fit=crop&crop=face',
        specialty: 'Pigmentação',
        rating: 4.9,
        reviewCount: 89,
        available: true,
    },
];

export const services: Service[] = [
    {
        id: '1',
        name: 'Corte Masculino',
        description: 'Corte tradicional com acabamento perfeito',
        duration: 30,
        price: 45,
        icon: 'cut-outline',
        category: 'corte',
    },
    {
        id: '2',
        name: 'Degradê',
        description: 'Degradê low, mid ou high fade',
        duration: 45,
        price: 55,
        icon: 'layers-outline',
        category: 'corte',
    },
    {
        id: '3',
        name: 'Barba Completa',
        description: 'Corte, desenho e hidratação da barba',
        duration: 30,
        price: 35,
        icon: 'man-outline',
        category: 'barba',
    },
    {
        id: '4',
        name: 'Combo Corte + Barba',
        description: 'Corte masculino + barba completa',
        duration: 60,
        price: 70,
        icon: 'star-outline',
        category: 'combo',
    },
    {
        id: '5',
        name: 'Sobrancelha',
        description: 'Design e alinhamento de sobrancelhas',
        duration: 15,
        price: 20,
        icon: 'eye-outline',
        category: 'outros',
    },
    {
        id: '6',
        name: 'Hidratação Capilar',
        description: 'Tratamento profundo para cabelos',
        duration: 45,
        price: 50,
        icon: 'water-outline',
        category: 'tratamento',
    },
    {
        id: '7',
        name: 'Pigmentação',
        description: 'Coloração e pigmentação capilar',
        duration: 60,
        price: 80,
        icon: 'color-palette-outline',
        category: 'tratamento',
    },
    {
        id: '8',
        name: 'Combo Premium',
        description: 'Corte + Barba + Sobrancelha + Hidratação',
        duration: 90,
        price: 120,
        icon: 'diamond-outline',
        category: 'combo',
    },
];

export const timeSlots: TimeSlot[] = [
    { time: '09:00', available: true },
    { time: '09:30', available: true },
    { time: '10:00', available: false },
    { time: '10:30', available: true },
    { time: '11:00', available: true },
    { time: '11:30', available: false },
    { time: '14:00', available: true },
    { time: '14:30', available: true },
    { time: '15:00', available: true },
    { time: '15:30', available: false },
    { time: '16:00', available: true },
    { time: '16:30', available: true },
    { time: '17:00', available: true },
    { time: '17:30', available: true },
    { time: '18:00', available: false },
    { time: '18:30', available: true },
];

export const mockBookings: Booking[] = [
    {
        id: '1',
        userId: '1',
        service: services[3],
        barber: barbers[0],
        date: '2026-02-03',
        time: '10:30',
        status: 'confirmed',
        totalPrice: 70,
        createdAt: '2026-01-30T14:00:00Z',
    },
    {
        id: '2',
        userId: '1',
        service: services[0],
        barber: barbers[1],
        date: '2026-01-28',
        time: '15:00',
        status: 'completed',
        totalPrice: 45,
        createdAt: '2026-01-25T10:00:00Z',
    },
    {
        id: '3',
        userId: '1',
        service: services[2],
        barber: barbers[0],
        date: '2026-01-20',
        time: '11:00',
        status: 'completed',
        totalPrice: 35,
        createdAt: '2026-01-18T09:00:00Z',
    },
];

export const mockUser = {
    id: '1',
    name: 'João Pedro',
    email: 'joao@email.com',
    phone: '(11) 99999-9999',
    avatar: 'https://images.unsplash.com/photo-1599566150163-29194dcabd36?w=150&h=150&fit=crop&crop=face',
};
